const ProductData = [
    {
        id: 1,
        name: 'PCL SERIES',
        title1: "IKOMA STANDARD ABSORBER WITH TWIN-TUBE SYSTEM.",
        title2: "Twin  Tube  System",
        imageUrl1: process.env.PUBLIC_URL + "/img/aa4eb-9ylb7.webp",
        imageUrl2: process.env.PUBLIC_URL + "/img/a1dov-2en0z.webp",
        font1:"Passenger Cars",
        font2:"Minivans",
        font3:"SUV",
        content1:"Best Piston Rod",
        text1:"Core component for shock absorber.IKOMA produce Piston Rod for ourselves 100 percent. Ensure all products quality control and make guarantee. Including heat treatment grinding electroplating and so on procedures. To increase durability and prevent oil-leakage situation happened on shock absorber.",
        content2:"Black or Colored Painting",
        text2:"Optional ED black electro coating or double layers anti-rust colored painting. Enable shock absorber prevent rust forming under the extreme weather to make sure of safety of products.",
        content3:"Enhanced welding",
        text3:"Exclusive welding machine and robot aimed welding, make the welding point and quality reach to same as OE standard. We IKOMA pay most attention not only best welding quality but also the beauty of weiding skills.",
        content4:"Anti-Oil leakage",
        text4:"Multi-lips unique double-sealed design can decrease obviously oil-leakage situation of shock absorber, besides if oil-leakage situation happened, will cause danger and reduce the performance of shock absorber.",
        content5:"Damper Setting",
        text5:"IKOMA Damper Setting basis on customers difference requirement to adjust. Especially for extreme rough or cold surroundings, IKOMA offers the special designs to be more suitable for those situations. For example: Two ways bearings and base valves, 5 levels damping force testing for 100% quantities inspection. It's your wisest choice for replacement IKOMA shock absorber.",
        textlist:"Feature: Using strut construction of Macpherson style, easy to fit the relative components of original suspension parts.Recover driving feeling to OEM one, even better also save money for purchasing shock absorber. IKOMA devote ourselves on quality and driving and seating comfort. Almost Anti-dust assembling line to make every finished work under clean and purity working surrounding. Performance and damper forces for each kind of shock absorber have the consistency and stable quality.",
    },
    {
        id: 2,
        name: 'PCI SERIES',
        title1: "IKOMA PERFORMANCE SHOCK ABSORBER WITH MONO-TYBE SYSTEM.",
        title2: "Twin Tube System",
        font1: "SUV",
        font2: "Trucks",
        imageUrl1: process.env.PUBLIC_URL + "/img/abel0-g1y7f.webp",
        imageUrl2: process.env.PUBLIC_URL + "/img/afqcz-bmk2d.webp",
        content1:"Enhanced Poston Rod",
        text1:"IKOMA X Series make it possible to drive wild bumpy road as normal road, due to use the much larger Piston Rod. Besides to increase thickness of electro-coating more than 50 percent.",
        content2:"Black or Colored Painting",
        text2:"Whatever selecting ED black electro coating or double layers anti-rust colored painting. IKOMA PCL X series shock absorber offer the best quality to prevent rust forming under the extreme weather to make sure of safety of products.",
        content3:"Advanced Enhancement for welding",
        text3:"Considering to enlarge the welding area and double welding improving the strength of welding. Offering the best safety of welding components and shock absorber.",
        content4:"Good Quality Rubber Accessories",
        text4:"Using the hardness increasing 30 percent rubber accessories and as well as the steel material of busing. Making ultra durability of eyering. Even low temperature or rough little stone hit, still work very well as usual.",
        content5:"Anti-dust oil seal design",
        text5:"Considering bumpy road or wild field surroundings, we design the anti-dust oil seals for most protection. Isolate the tiny sand and stone particles come into shock absorber and avoid damage to piston rod or other components. Suitable for your requirement for using vehicle on the extreme surroundings.",
        content6:"Damper Force settlement",
        text6:"IKOMA offer much enhanced damper force settlement, increasing the driving handling ability and mobility of vehicle.",
        textlist:"Feature: Using strut construction of Macpherson style, easy to fit the relative components of original suspension parts. Recover driving feeling to OEM one, even better also save money for purchasing shock absorber. IKOMA devote ourselves on quality and driving and seating comfort. Almost Anti-dust assembling line to make every finished work under clean and purity working surrounding. Performance and damper forces for each kind of shock absorber have the consistency and stable quality.Not only suitable for Sedan or light wild field SUV, we focus on each different using area to adjust damper force, to eliminate vibration and rolling un-stability. Moreover for rough road condition and need special adjusting travel length and heat radiation using, we will make modification for suitable products.IKOMA always consider about customer unique requirement to adjust our products to satisty any needed.- Two ways twin tube construction: let exchange heat from outer oil tube chamber to inner tube chamber easy then others, let damper force maintain stability.- Special double inner and outer oil seals design, let anti-dust and sealed oil seals have most efficiency for working.- Unique valves add the stream flow between outer-inner oil chambers, let shock absorber always keeps low temperature with high performance.- Advanced Anti-Dust design-Despite some tiny dusts come into shock absorber, still can work smoothly with no problem.",
    },
    {
        id: 3,
        name: 'PCL-X SERIES',
        title1: "IKOMA STANDARD ABSORBER WITH TWIN-TUBE SYSTEM.",
        title2: "Mono Tube System",
        font1: "Passenger Cars",
        font2: "Minivans",
        font3: "SUV",
        imageUrl1: process.env.PUBLIC_URL + "/img/a7063-lqqsr.webp",
        imageUrl2: process.env.PUBLIC_URL + "/img/adize-cg4bv.webp",
        imageUrl3: process.env.PUBLIC_URL + "/img/a6nkv-0rsn8.webp",
        content1:"Piston Rod x Piston",
        text1:"IKOMA PCI series use 3 kind different constructions, base on different chassis and car models characters. Let PCI series shock absorber have full performance for most SUV and Truck.",
        content2:"Painting and coating for considering durability",
        text2:"Comply to RoHs regulation painting and coating, easy to spread out the heat and anti-rust purpose.",
        content3:"Outstanding Quality Rubber Accessories:",
        text3:"Using the hardness increasing 30 percent rubber accessories and as well as the steel material of busing. Making ultra durability of eyering. Even low temperature or rough little stone hit, still work very well as usual.",
        content4:"Mono Tube High rigidity valve",
        text4:"IKOMA choose the high rigidity valve to keep the high performance damper force don't drop in the short time.Besides using the special material valves can be flexible under extreme high speed travels.",
        content5:"Damper Settling",
        text5:"Boosting advantage of Mono Tube, upgrade driving control. IKOMA make best damper settling for each car model to optimize handling.",
        textlist:"Construction of Mono Tube shock absorber has better performance damper than other construction. Not only larger piston but also total solution for shock absorber.Due to apply on most non-strut car model, IKOMA PCI series pay great attention on the precision for components with high pressure Nitrogen. Outstanding quality of components and better exclusive assemble line let PCI series have best durability and more stable damper force than others.- Advanced dust cover design, Isolate the invasion of dust and sand into shock absorber.- Exclusive shock absorber oil to make most fitting for mono tube construction. And increase the durability of shock absorber.- Free Piston made of standard 6061 T6 material with high hardness of O ring. Make effectively separation between oil chamber with gas chamber.",
    }
];

export default ProductData;